# Generated by Django 2.1.4 on 2019-01-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_pad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='locate',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pad',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
